name: Create an RDev Stack

on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  create-rdev-stack:
    runs-on: [ARM64, self-hosted, Linux]
    if: contains(github.event.pull_request.labels.*.name, 'stack')
    permissions:
        id-token: write
        contents: read

    steps:
      - name: Create Stack
        uses: chanzuckerberg/argus-artifacts/ci/packages/create-stack@v0.7.1
        with:
          appName: single-cell-explorer
          envName: rdev
