name: Create an RDev Stack

on:
  pull_request:
    types: [ labeled, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-rdev-stack:
    runs-on: [ARM64, self-hosted, Linux]
    if: contains(github.event.pull_request.labels.*.name, 'stack')
    permissions:
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Create Stack
        uses: chanzuckerberg/argus-artifacts/ci/packages/create-stack@v0.23.0
        with:
          appName: single-cell-explorer
          envName: rdev

  rdev-smoke-test:
    uses: ./.github/workflows/workflow-smoke-test.yaml
    needs: create-rdev-stack
    secrets: inherit
    with:
      env: dev
